# fly.toml app configuration file generated for lab4-morning-hill-4678 on 2025-03-21T20:15:18+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lab4-morning-hill-4678'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'



[[services]]
  internal_port = 8000
  protocol = 'tcp'

  [services.concurrency]
    hard_limit = 25
    soft_linit = 20
    type = 'connections'

  [[services.ports]]
    handlers = ['http]
    port = 80

  [[services.ports]]
    handlers = ['tls', 'http']
    port = 443

[[vm]]
  size = 'shared-cpu-1x'
